Program 0x51
Bgm 112 112
BattleLevel 35
AreaSettings 7 -1
	SetUnk05 0x3
	SetJump Type 2 World MU Area 0 Entrance 0 LocalSet 78 FadeType 1
	SetPartyMenu 0

Program 0x4F
Bgm 115 115
BattleLevel 35
AreaSettings 16 -1
	SetUnk05 0x1
	SetJump Type 2 World BB Area 0 Entrance 0 LocalSet 75 FadeType 1
	SetPartyMenu 0

Program 0x4A
Bgm 112 112
BattleLevel 10
AreaSettings 7 -1
	SetProgressFlag 0x143B
	SetUnk05 0x3
	SetJump Type 2 World MU Area 0 Entrance 0 LocalSet 75 FadeType 1
	SetPartyMenu 0
