Program 0x3A
Party W_FRIEND
Bgm 111 111
BattleLevel 45
AreaSettings 16 -1
	SetProgressFlag 0x868
	SetUnk05 0x3
	SetJump Type 1 World TT Area 32 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "e_03"

Program 0x3B
Party W_FRIEND
Bgm 110 110
BattleLevel 45
AreaSettings 16 -1
	SetProgressFlag 0x869
	SetUnk05 0x3
	SetJump Type 1 World TT Area 32 Entrance 50 LocalSet 0 FadeType 1
	SetPartyMenu 0

Spawn "e_04"
